# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eaaa9350972062c989efb5fe9755af8dd8ab01561915d31452a842ba2377b5c78f925c586024ceb6a79047d4c53760e68065f926645ce3664089e471d70fadd

test:
  secret_key_base: 25a0b5deb0c65ed630243559084d1a76570fe832f1543fd2bc9f951439a412c27c49ff86ae7ca15115c9f71e19601fe99267e4df8d2819412d40a9394774bdc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
